import os
os.system('cls')

# AQUI COMEÇAMOS COM O WHILE
while True:
    # AQUI COLOCAMOS O QUE SERA EXECUTADO CONFORME O QUE FOI PEDIDO.
    nota = float(input('Digite uma nota entre 0 a 10: '))
    # AQUI ADICIONAMOS O IF DENTRO DO WHILE PARA DAR COMANDO COM SE/SENAO.
    if nota < 0 or nota > 10:
        print('Nota invalida. ')
        print('Tente novamente! \n ')
        # AQUI FICA O SENAO, ONDE EU QUERO QUE CASO A NOTA ESTEJA CORRETA, SENAO MOSTRE A NOTA CORRETA
    else:
        print(f'Nota: {nota}')
        # AQUI ESTA O BREAK, SINALIZANDO QUE CASO A NOTA ESTEJA CORRETA ENTAO PARE O LOOP IMEDIATAMENTE.
        break

# AQUI É O SEGUINTE O WHILE TRUE VEM PRIMEIRO E DEPOIS COMEÇO A MONTAR O CODIGO ABAIXO DO WHILE
# E ENTAO VOU PEDIR PARA QUE REPITA QUANTAS VEZES EU QUISER SEM NENHUMA FORMA DE PAUSA, E ENTAO
# QUANDO ELE ACERTAR O QUE O USUARIO PEDE, QUERO QUE O LOOP PARE IMEDIATAMENTE.